services:
  - type: web
    name: lakshmi-ai-wife
    env: python
    buildCommand: pip install --upgrade pip && pip install --no-build-isolation -r requirements.txt
    startCommand: gunicorn app:app
